In [1]:
import numpy as np
def g(mean,prior,x):
    return mean.T.dot(x) - 0.5*mean.T.dot(mean) + np.log(prior)

In [12]:
x = np.array([[-1,0.9],[1,0.8],[1,1.1],[-1.2,1.1]])
mean0 = np.array([-1.2,1.1])
mean1 = np.array([-1,0.9])
prior0,prior1 = 0.5,0.5

In [13]:
np.mean(x,axis = 0)

array([-0.05 ,  0.975])

In [17]:
iteration = 3
for k in range(iteration):
    x0_new,x1_new = [],[]
    for i in range(x.shape[0]):
        g0 = g(mean0,prior0,x[i])
        g1 = g(mean1,prior1,x[i])
        if g0 > g1: x0_new.append(x[i])
        else: x1_new.append(x[i])
    print(x0_new,x1_new)
    prior0 = len(x0_new) / 4
    prior1 = 1 - prior0
    x0 = np.array(x0_new)
    x1 = np.array(x1_new)
    mean0 = np.mean(x0,axis = 0)
    mean1 = np.mean(x1,axis = 0)
print(mean0,mean1)

[array([-1.2,  1.1])] [array([-1. ,  0.9]), array([1. , 0.8]), array([1. , 1.1])]
[array([-1.2,  1.1])] [array([-1. ,  0.9]), array([1. , 0.8]), array([1. , 1.1])]
[array([-1.2,  1.1])] [array([-1. ,  0.9]), array([1. , 0.8]), array([1. , 1.1])]
[-1.2  1.1] [0.33333333 0.93333333]


In [18]:
x0

array([[-1.2,  1.1]])

In [19]:
x1

array([[-1. ,  0.9],
       [ 1. ,  0.8],
       [ 1. ,  1.1]])

In [20]:
prior0

0.25

In [21]:
prior1

0.75